const controller=require('../controllers/function')
const express = require('express')
const router=express.Router()
router.get('/store_cpu',controller.cpu) 
router.get('/store_cpu_load',controller.cpu_load) 
router.get('/store_ram',controller.ram) 
router.get('/store_throughput_data',controller.throughput_data) 
router.get('/store_io_operations_data',controller.io_operations_data) 
router.get('/store_disk_average_wait_data',controller.disk_average_wait_data) 
router.get('/store_no_of_thread',controller.no_of_thread) 
router.get('/store_lama_app_failureauth',controller.lama_app_failureauth) 
router.get('/store_lama_app_latency',controller.lama_app_latency) 
router.get('/store_lama_app_throughput',controller.lama_app_throughput) 
router.get('/store_tcp_connection',controller.tcp_connection) 
router.get('/store_up_time',controller.up_time) 
router.get('/store_hhd',controller.hhd) 
router.get('/store_interface',controller.interface) 
router.get('/store_details',controller.details) 

module.exports=router;
